SITES/annova/site/passport/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from django.conf.urls import url

from apps.site.passport import views

app_name = 'passport'
urlpatterns = [
    # получение по апи всех данных (секретно)
    #url('^(?P<action>passport)/api/$', views.api, name='api'),
    # админка
    path('admin/', views.show_passports, name='show_passports'),
    url('^admin/(?P<action>create)/$', views.edit_passport, name='create_passport'),
    url('^admin/(?P<action>edit|drop|img)/(?P<row_id>[0-9]{1,11})/$', views.edit_passport, name='edit_passport'),
    path('admin/positions/', views.passports_positions, name='passports_positions'),
    # аякс-поиск
    path('passports/search/', views.search_passports, name='search_passports'),
]

apps/personal/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'personal'
urlpatterns = [
    # получение по апи всех данных (секретно, по токену?)
    #url('^(?P<action>shoppers)/api/$', views.api, name='api'),
    # админка
    path('admin/', views.show_shoppers, name='show_shoppers'),
    url('^admin/(?P<action>create)/$', views.edit_shopper, name='create_shopper'),
    url('^admin/(?P<action>edit|drop|img)/(?P<row_id>[0-9]{1,11})/$', views.edit_shopper, name='edit_shopper'),
    path('admin/positions/', views.shoppers_positions, name='shoppers_positions'),
    # аякс-поиск
    path('shoppers/search/', views.search_shoppers, name='search_shoppers'),
    # OAuth авторизация пользователей
    path('oauth/test/', views.oauth_test, name='oauth_test'),
    path('oauth/vk/', views.oauth_vk, name='oauth_vk'),
    path('oauth/yandex/', views.oauth_yandex, name='oauth_yandex'),
]

conf/urls.py
from django.conf import settings
from django.urls import path, include, re_path
from django.shortcuts import redirect
from django.conf.urls import url


urlpatterns = [
    re_path(r'^admin/', include('apps.login.urls')),
    path('auth/', lambda request: redirect('/admin/', permanent=False)),
    # Стат. странички
    re_path(r'^flatcontent/', include('apps.flatcontent.urls')),
    # Файлы
    re_path(r'^files/', include('apps.files.urls')),
    # main_functions
    re_path(r'^', include('apps.main_functions.urls')),
    # Telegram
    re_path(r'^telegram/', include('apps.telegram.urls')),
    # статика
    re_path(r'^', include('apps.files.urls_static'))
]

# ---------------------------------
# Подключение приложений через .env
# ---------------------------------
if 'apps.site' in settings.INSTALLED_APPS:
    # Сайт
    urlpatterns.insert(1, re_path(r'^', include('apps.site.main.urls')))
# ---------------------------
# Подключаем custom site apps
# ---------------------------
for app in settings.INSTALLED_APPS:
    if app.startswith('apps.site.'):
        prefix = app.split('.')[-1]
        urlpatterns.insert(1, re_path(r'^%s/' % prefix, include('%s.urls' % app)))

if 'apps.afisha' in settings.INSTALLED_APPS:
    # Афиша
    urlpatterns += [
        re_path(r'^afisha/', include('apps.afisha.urls')),
    ]
if 'apps.spamcha' in settings.INSTALLED_APPS:
    from apps.spamcha.views import srdr_goto
    # Рассылки
    urlpatterns += [
        re_path(r'^spamcha/', include('apps.spamcha.urls')),
        # -----------------------------
        # /srdr/goto/.../ Переадресация
        # -----------------------------
        url('^srdr/goto/(?P<our_link>.+)/$', srdr_goto, name='srdr_goto'),
    ]
if 'apps.ws' in settings.INSTALLED_APPS:
    # websocket (chat)
    urlpatterns += [
        re_path(r'^ws/', include('apps.ws.urls')),
    ]
if 'apps.binary_com' in settings.INSTALLED_APPS:
    # binary.com
    urlpatterns += [
        re_path(r'^binary_com/', include('apps.binary_com.urls')),
    ]
if 'apps.languages' in settings.INSTALLED_APPS:
    # Переводы
    urlpatterns += [
        re_path(r'^languages/', include('apps.languages.urls')),
    ]
if 'apps.freeswitch' in settings.INSTALLED_APPS:
    # FREESWITCH
    urlpatterns += [
        re_path(r'^freeswitch/', include('apps.freeswitch.urls')),
    ]
if 'apps.demonology' in settings.INSTALLED_APPS:
    # Создание демонов
    urlpatterns += [
        re_path(r'^demonology/', include('apps.demonology.urls')),
    ]
if 'apps.products' in settings.INSTALLED_APPS:
    # Товары/услуги
    urlpatterns += [
        re_path(r'^products/', include('apps.products.urls')),
    ]
if 'apps.promotion' in settings.INSTALLED_APPS:
    # Продвижение и сео
    urlpatterns += [
        re_path(r'^promotion/', include('apps.promotion.urls')),
    ]
if 'apps.personal' in settings.INSTALLED_APPS:
    # Пользователи сайта
    urlpatterns += [
        re_path(r'^personal/', include('apps.personal.urls')),
    ]
if 'apps.yandex' in settings.INSTALLED_APPS:
    # Яндекс сервисы
    urlpatterns += [
        re_path(r'^yandex/', include('apps.yandex.urls')),
    ]
if 'apps.shop' in settings.INSTALLED_APPS:
    # Магазин
    urlpatterns += [
        re_path(r'^shop/', include('apps.shop.urls')),
    ]
if 'apps.net_tools' in settings.INSTALLED_APPS:
    # Модуль сетевых утилит
    urlpatterns += [
        re_path(r'^net_tools/', include('apps.net_tools.urls')),
    ]
if 'apps.addresses' in settings.INSTALLED_APPS:
    # Адреса объектов
    urlpatterns += [
        re_path(r'^addresses/', include('apps.addresses.urls')),
    ]
if 'apps.contractors' in settings.INSTALLED_APPS:
    # Контрагенты
    urlpatterns += [
        re_path(r'^contractors/', include('apps.contractors.urls')),
    ]
if 'apps.jabber' in settings.INSTALLED_APPS:
    # Jabber XMPP
    urlpatterns += [
        re_path(r'^jabber/', include('apps.jabber.urls')),
    ]
if 'apps.former' in settings.INSTALLED_APPS:
    # Конструктор форм
    urlpatterns += [
        re_path(r'^former/', include('apps.former.urls')),
    ]
if 'djapian' in settings.INSTALLED_APPS:
    # DJAPIAN SEARCH
    from djapian.utils import load_indexes
    load_indexes()

# -------------------------------------------
# Обработка статических файлов под DEBUG=True
# -------------------------------------------
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# --------------
# Стат странички
# --------------
urlpatterns += [
    re_path(r'^', include('apps.flatcontent.urls_static')),
]

SITES/annova/site/passport/models.py
# -*- coding: utf-8 -*-
from django.db import models

from apps.main_functions.models import Standard
from apps.flatcontent.models import Blocks
from apps.personal.models import Shopper

class Passport(Standard):
    """Паспортные данные
    """
    passport_choices = (
        (1, 'Паспорт гражданина РФ'),
        (2, 'Загранпаспорт гражданина РФ'),
        (3, 'Свидетельство о рождении'),
    )
    shopper = models.ForeignKey(Shopper,
        blank=True, null=True,
        on_delete = models.SET_NULL,
        verbose_name='Пользователь')
    birthday = models.DateField(blank=True, null=True, db_index=True,
        verbose_name='Дата рождения')
    series = models.CharField(max_length=64,
        blank=True, null=True, db_index=True,
        verbose_name='Серия паспорта')
    number = models.CharField(max_length=64,
        blank=True, null=True, db_index=True,
        verbose_name='Номер паспорта')
    issued = models.CharField(max_length=255,
        blank=True, null=True, db_index=True,
        verbose_name='Кем выдан')
    issued_date = models.DateField(blank=True, null=True, db_index=True,
        verbose_name='Когда выдан')
    registration = models.CharField(max_length=255,
        blank=True, null=True, db_index=True,
        verbose_name='Адрес регистрации')
    ptype = models.IntegerField(choices=passport_choices,
        blank=True, null=True, db_index=True,
        verbose_name='Тип паспорта: рф/загран'
    )

    class Meta:
        verbose_name = 'Пользователь - Паспортные данные'
        verbose_name_plural = 'Пользователь - Паспортные данные'
        #permissions = (
        #    ('view_obj', 'Просмотр объектов'),
        #    ('create_obj', 'Создание объектов'),
        #    ('edit_obj', 'Редактирование объектов'),
        #    ('drop_obj', 'Удаление объектов'),
        #)
        #default_permissions = []

    def save(self, *args, **kwargs):
        super(Passport, self).save(*args, **kwargs)

SITES/annova/site/passport/views.py
# -*- coding:utf-8 -*-
import json

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.urls import reverse, resolve
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import Q

from apps.main_functions.functions import object_fields
from apps.main_functions.model_helper import create_model_helper, tabulator_filters_and_sorters
from apps.main_functions.api_helper import ApiHelper, XlsxHelper
from apps.main_functions.views_helper import (
    show_view,
    edit_view,
    search_view,
    special_model_vars,
)
from apps.site.passport.models import Passport

CUR_APP = 'passport'
passport_vars = {
    'singular_obj': 'Паспортные данные',
    'plural_obj': 'Паспортные данные',
    'rp_singular_obj': 'паспортных данных',
    'rp_plural_obj': 'паспортных данных',
    'template_prefix': 'passport_',
    'action_create': 'Создание',
    'action_edit': 'Редактирование',
    'action_drop': 'Удаление',
    'menu': 'passport',
    'submenu': 'passport',
    'show_urla': 'show_passports',
    'create_urla': 'create_passport',
    'edit_urla': 'edit_passport',
    'model': Passport,
    #'custom_model_permissions': Phones,
    'select_related_list': ('shopper', ),
}

def api(request, action: str = 'passport'):
    """Апи-метод для получения всех данных
       :param request: HttpRequest
       :param action: к какой модели обращаемся
    """
    #if action == 'phones':
    #    result = ApiHelper(request, passport_vars, CUR_APP)
    result = ApiHelper(request, passport_vars, CUR_APP)
    return result

@login_required
def show_passports(request, *args, **kwargs):
    """Вывод паспортных данных
       :param request: HttpRequest
    """
    mh_vars = passport_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP)
    mh.select_related_add('shopper')
    context = mh.context
    special_model_vars(mh, mh_vars, context)
    # -----------------------------
    # Вся выборка только через аякс
    # -----------------------------
    if request.is_ajax():
        only_fields = (
            'id',
            'shopper__name',
            'shopper__phone',
            'birthday',
            'series',
            'number',
            'issued',
            'issued_date',
            'registration',
        )
        fk_keys = {
            'shopper': ('name',
                        'phone'),
        }
        rows = mh.standard_show(only_fields=only_fields)
        result = []
        for row in rows:
            item = object_fields(row,
                                 only_fields=only_fields,
                                 fk_only_keys=fk_keys)
            item['actions'] = row.id
            item['folder'] = row.get_folder()
            item['thumb'] = row.thumb()
            item['imagine'] = row.imagine()
            result.append(item)
        if request.GET.get('page'):
            result = {'data': result,
                      'last_page': mh.raw_paginator['total_pages'],
                      'total_records': mh.raw_paginator['total_records'],
                      'cur_page': mh.raw_paginator['cur_page'],
                      'by': mh.raw_paginator['by'], }
        return JsonResponse(result, safe=False)
    template = '%stable.html' % (mh.template_prefix, )
    return render(request, template, context)

@login_required
def edit_passport(request, action: str, row_id: int = None, *args, **kwargs):
    """Создание/редактирование паспортных данных
       :param request: HttpRequest
       :param action: действие над объектом (создание/редактирование/удаление)
       :param row_id: ид записи
    """
    return edit_view(request,
                     model_vars = passport_vars,
                     cur_app = CUR_APP,
                     action = action,
                     row_id = row_id,
                     extra_vars = None, )

@login_required
def passports_positions(request, *args, **kwargs):
    """Изменение позиций паспортных данных
       :param request: HttpRequest
    """
    result = {}
    mh_vars = passport_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP, 'positions')
    result = mh.update_positions()
    return JsonResponse(result, safe=False)

def search_passports(request, *args, **kwargs):
    """Поиск паспортных данных
       :param request: HttpRequest
    """
    return search_view(request,
                       model_vars = passport_vars,
                       cur_app = CUR_APP,
                       sfields = None, )

SITES/annova/site/passport/templates/passport_admin_menu.html
{% if perms.passport.view_passport %}
<li{% ifequal menu 'passport' %} class="active"{% endifequal %} id="left_menu_passport_app">
  <a href="{% url 'passport:show_passports' %}">
    <em class="fa fa-file-text"></em>
    <span class="item-text">Паспортные данные</span>
  </a>
</li>
{% endif %}

SITES/annova/site/passport/templates/passport_edit.html
{% extends "core/base.html" %}

{% block extrahead %}
<link href="/static/datetimepicker/datepicker.min.css" rel="stylesheet"/>
{% endblock %}

{% block content %}

{% include "core/title/page_title_edit.html" %}
{% include "core/breadcrumbs.html" %}
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <form class="form-horizontal" method="post" action="{% if action == 'create' %}{{ url_create }}{% endif %}{% if action == 'edit' %}{{ url_edit }}{% endif %}" id="current_edit_form">
        <div class="panel-heading">{{ singular_obj }}</div>
        <div class="panel-body">
          {% csrf_token %}
          <div class="form-group">
            <label class="col-lg-2 control-label">Пользователь</label>
            <div class="col-lg-10">
              <select id="shopper_select2" name="shopper" autocomplete="off" data-parsley-required>
                {% if row.shopper %}
                  <option value="{{ row.shopper.id }}" selected>{{ row.shopper.name }} #{{ row.shopper.id }}</option>
                {% endif %}
              </select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Дата рождения</label>
            <div class="col-lg-10">
              <input type="text" id="birthday_date" placeholder="Дата рождения" class="form-control" name="birthday" value="{% if row.birthday %}{{ row.birthday }}{% endif %}" autocomplete="off">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Серия паспорта</label>
            <div class="col-lg-10">
              <input type="text" placeholder="Серия паспорта" class="form-control" name="series" value="{% if row.series %}{{ row.series }}{% endif %}" autocomplete="off">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Номер паспорта</label>
            <div class="col-lg-10">
              <input type="text" placeholder="Номер паспорта" class="form-control" name="number" value="{% if row.number %}{{ row.number }}{% endif %}" autocomplete="off">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Кем выдан</label>
            <div class="col-lg-10">
              <input type="text" placeholder="Кем выдан" class="form-control" name="issued" value="{% if row.issued %}{{ row.issued }}{% endif %}" autocomplete="off">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Когда выдан</label>
            <div class="col-lg-10">
              <input type="text" id="issued_date" placeholder="Когда выдан" class="form-control" name="issued_date" value="{% if row.issued_date %}{{ row.issued_date }}{% endif %}" autocomplete="off">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Место регистрации</label>
            <div class="col-lg-10">
              <input type="text" placeholder="Место регистрации" class="form-control" name="registration" value="{% if row.registration %}{{ row.registration }}{% endif %}" autocomplete="off">
            </div>
          </div>
          {% include "core/forms/row_image.html" %}
          {% include "core/forms/row_position.html" %}
          {% include "core/forms/row_is_active.html" %}
        </div>
        {% include "core/forms/footer_buttons.html" %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extrascripts %}
<script src="/static/admin/js/parsley.min.js"></script>
<script type="text/javascript" src="/static/datetimepicker/datepicker.min.js"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $("#current_edit_form").parsley();
    $("#current_edit_form").submit(function(e) {
      var $form = $(this);
      var msg = 'Произошла ошибка, обновите страничку';
      var status = 'danger'; // success, warning, info, danger
      $.ajax({
        type: $form.attr('method'),
        url: $form.attr('action'),
        data: $form.serialize()
      }).done(function(r) {
        if(r.error){
          msg = r.error;
        }else if(r.success){
          msg =  r.success;
          status = 'success';
          //$("#current_edit_form").attr("action", r.redirect);
          {% ifequal action 'create' %}window.location.href = r.redirect;{% endifequal %}
        }
        $.notify({
          message: msg,
        },{
          status: status,
        });
        // Обновление ссылок
        update_links(r);
      }).fail(function() {
        $.notify({
          message: msg,
        },{
          status: status,
        });
      });
      //отмена действия по умолчанию для кнопки submit
      e.preventDefault();
    });

    $("#birthday_date").datepicker({
      onSelect: function (fd, d, calendar) {
        calendar.hide();
      },
      todayButton: new Date(),
    });
    $("#issued_date").datepicker({
      onSelect: function (fd, d, calendar) {
        calendar.hide();
      },
      todayButton: new Date(),
    });

    $('#shopper_select2').select2({
      placeholder: 'Пользователь',
      allowClear: true,
      width: '100%',
      tags: false,
      ajax: {
        url: "{% url 'personal:search_shoppers' %}",
        data: function (params) {
          var query = {
            q: params.term,
            page: params.page || 1,
          }
          return query;
        },
        cache: false,
        dataType: 'json',
      }
    });

    function update_links(r){
      var thumb = r['row']['thumb'];
      if(thumb === ''){
        thumb = '/static/img/empty.png';
      }
      $("#preview_img").attr("src", thumb + "?_=" + Date.now());
    }
    {% if row %}
      var progressbar = $('#progressbar-files'),
        bar         = progressbar.find('.progress-bar-files'),
        settings    = {
          action: '{% url "passport:edit_passport" "img" row.id %}', // upload url
          allow : '*.*',
          param: 'img',
          params: {csrfmiddlewaretoken: getCookie('csrftoken')},
          loadstart: function() {
            bar.css('width', '0%').text('0%');
            progressbar.removeClass('hidden');
          },
          progress: function(percent) {
            percent = Math.ceil(percent);
            bar.css('width', percent+'%').text(percent+'%');
          },
          allcomplete: function(response) {
            bar.css('width', '100%').text('100%');
            setTimeout(function(){
              progressbar.addClass('hidden');
            }, 750);
            // Upload Completed
              //alert(response);

            // Обновление ссылок
            var r = JSON.parse(response);
            update_links(r);
          }
        };
      var select = new $.upload.select($('#upload-select-files'), settings),
      drop   = new $.upload.drop($('#upload-drop-files'), settings);
    {% endif %}
  });
</script>
{% endblock %}

SITES/annova/site/passport/templates/passport_table.html
{% extends "core/base.html" %}

{% block extrahead %}
{% endblock %}

{% block content %}
{% include "core/forms/default_create.html" %}

{% include "core/title/page_title_table.html" %}
{% include "core/breadcrumbs.html" %}

{% include "core/tabulator_table.html" %}
{% endblock %}

{% block extrascripts %}
<script src="/static/admin/js/parsley.min.js"></script>
<script type="text/javascript">
var main_table = null;
var main_table_columns = null;

$(document).ready(function(){

  main_table_columns = [
    {% include "core/tabulator_cell/drag.html" %}
    {% include "core/tabulator_cell/id.html" %}
    {
      title: "Имя",
      field: "shopper.name",
      headerFilterPlaceholder: "Имя",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 120,
    },
    {
      title: "Телефон",
      field: "shopper.phone",
      headerFilterPlaceholder: "Телефон",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 120,
    },
    {
      title: "Серия паспорта",
      field: "series",
      headerFilterPlaceholder: "Серия паспорта",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 90,
    },
    {
      title: "Номер паспорта",
      field: "number",
      headerFilterPlaceholder: "Номер паспорта",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 120,
    },
    {
      title: "Кем выдан",
      field: "issued",
      headerFilterPlaceholder: "Кем выдан",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 120,
    },
    {
      title: "Когда выдан",
      field: "number",
      headerFilterPlaceholder: "Когда выдан",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 120,
    },
    {
      title: "Регистрация",
      field: "registration",
      headerFilterPlaceholder: "Регистрация",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 120,
    },
    {% include "core/tabulator_cell/image.html" %}
    {% include "core/tabulator_cell/is_active.html" %}
    {% include "core/tabulator_cell/position.html" %}
    {% include "core/tabulator_cell/actions.html" %}
  ]
  main_table = new Tabulator("#main-table", {
    {% include "core/tabulator_table_params.html" %}
    columns: main_table_columns,
  });

  $(".tabulator-headers .tabulator-col").each(function(){
    if($(this).attr("tabulator-field") === "cat"){
      $("#menu_filter").select2({
        placeholder: 'Выберите меню',
        width: '100%',
        //tags: true,
        allowClear: true,
        ajax: {
          delay: 150,
          url: "{% url 'flatcontent:search_blocks' %}",

          data: function (params) {
            var query = {
              q: params.term,
              filter__container__tag: 'phones8800',
              page: params.page || 1,
            }
            return query;
          },
          cache: false,
          dataType: 'json',
        }
      }).change(function(){
        //console.log('cat', $(this).val());
        var select = document.querySelector("#menu_filter");
        select.value = $(this).val();
        // changed - custom event (instead of change)
        select.dispatchEvent(new Event('changed'));
      });
    }
  });
});
</script>
{% endblock %}