SITES/nosite/site/robots/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'robots'
urlpatterns = [
    # получение по апи всех данных (т/к не секретно)
    url('^(?P<action>robots|test_scenarios|search_queries|sites)/api/$', views.api, name='api'),
    url('^(?P<action>search_queries)/import_xlsx/$', views.import_xlsx, name='import_xlsx'),
    # админка - роботы
    path('admin/', views.show_robots, name='show_robots'),
    url('^admin/(?P<action>create)/$', views.edit_robot, name='create_robot'),
    url('^admin/(?P<action>edit|drop|img)/(?P<row_id>[0-9]{1,11})/$', views.edit_robot, name='edit_robot'),
    path('admin/positions/', views.robots_positions, name='robots_positions'),
    path('robots/search/', views.search_robots, name='search_robots'),
    # админка - сценарии
    path('admin/test_scenarios/', views.show_test_scenarios, name='show_test_scenarios'),
    url('^admin/test_scenarios/(?P<action>create)/$', views.edit_test_scenario, name='create_test_scenario'),
    url('^admin/test_scenarios/(?P<action>edit|drop|img)/(?P<row_id>[0-9]{1,11})/$', views.edit_test_scenario, name='edit_test_scenario'),
    path('admin/test_scenarios/positions/', views.test_scenarios_positions, name='test_scenarios_positions'),
    path('test_scenarios/search/', views.search_test_scenarios, name='search_test_scenarios'),
    # админка - сайты
    path('admin/sites/', views.show_sites, name='show_sites'),
    url('^admin/sites/(?P<action>create)/$', views.edit_site, name='create_site'),
    url('^admin/sites/(?P<action>edit|drop|img)/(?P<row_id>[0-9]{1,11})/$', views.edit_site, name='edit_site'),
    path('admin/sites/positions/', views.sites_positions, name='sites_positions'),
    path('sites/search/', views.search_sites, name='search_sites'),
    # админка - профили роботов
    path('admin/robot_profiles/', views.show_robot_profiles, name='show_robot_profiles'),
    url('^admin/robot_profiles/(?P<action>create)/$', views.edit_robot_profile, name='create_robot_profile'),
    url('^admin/robot_profiles/(?P<action>edit|drop|img)/(?P<row_id>[0-9]{1,11})/$', views.edit_robot_profile, name='edit_robot_profile'),
    path('admin/robot_profiles/positions/', views.robot_profiles_positions, name='robot_profiles_positions'),
    path('robot_profiles/search/', views.search_robot_profiles, name='search_robot_profiles'),
    # админка - поисковые запросы
    path('admin/search_queries/', views.show_search_queries, name='show_search_queries'),
    url('^admin/search_queries/(?P<action>create)/$', views.edit_search_query, name='create_search_query'),
    url('^admin/search_queries/(?P<action>edit|drop|img)/(?P<row_id>[0-9]{1,11})/$', views.edit_search_query, name='edit_search_query'),
    path('admin/search_queries/positions/', views.search_queries_positions, name='search_queries_positions'),
    path('search_queries/search/', views.search_search_queries, name='search_search_queries'),

    # апи - информация от робота
    path('inform_server/', views.inform_server, name='inform_server'),
    # апи - обновление робота
    path('updater/', views.updater, name='updater'),
]

conf/urls.py
from django.conf import settings
from django.urls import path, include, re_path
from django.shortcuts import redirect
from django.conf.urls import url


urlpatterns = [
    re_path(r'^admin/', include('apps.login.urls')),
    path('auth/', lambda request: redirect('/admin/', permanent=False)),
    # Стат. странички
    re_path(r'^flatcontent/', include('apps.flatcontent.urls')),
    # Файлы
    re_path(r'^files/', include('apps.files.urls')),
    # main_functions
    re_path(r'^', include('apps.main_functions.urls')),
    # Telegram
    re_path(r'^telegram/', include('apps.telegram.urls')),
    # статика
    re_path(r'^', include('apps.files.urls_static'))
]

# ---------------------------------
# Подключение приложений через .env
# ---------------------------------
if 'apps.site' in settings.INSTALLED_APPS:
    # Сайт
    urlpatterns.insert(1, re_path(r'^', include('apps.site.main.urls')))
# ---------------------------
# Подключаем custom site apps
# ---------------------------
for app in settings.INSTALLED_APPS:
    if app.startswith('apps.site.'):
        prefix = app.split('.')[-1]
        urlpatterns.insert(1, re_path(r'^%s/' % prefix, include('%s.urls' % app)))

if 'apps.afisha' in settings.INSTALLED_APPS:
    # Афиша
    urlpatterns += [
        re_path(r'^afisha/', include('apps.afisha.urls')),
    ]
if 'apps.spamcha' in settings.INSTALLED_APPS:
    from apps.spamcha.views import srdr_goto
    # Рассылки
    urlpatterns += [
        re_path(r'^spamcha/', include('apps.spamcha.urls')),
        # -----------------------------
        # /srdr/goto/.../ Переадресация
        # -----------------------------
        url('^srdr/goto/(?P<our_link>.+)/$', srdr_goto, name='srdr_goto'),
    ]
if 'apps.ws' in settings.INSTALLED_APPS:
    # websocket (chat)
    urlpatterns += [
        re_path(r'^ws/', include('apps.ws.urls')),
    ]
if 'apps.binary_com' in settings.INSTALLED_APPS:
    # binary.com
    urlpatterns += [
        re_path(r'^binary_com/', include('apps.binary_com.urls')),
    ]
if 'apps.languages' in settings.INSTALLED_APPS:
    # Переводы
    urlpatterns += [
        re_path(r'^languages/', include('apps.languages.urls')),
    ]
if 'apps.freeswitch' in settings.INSTALLED_APPS:
    # FREESWITCH
    urlpatterns += [
        re_path(r'^freeswitch/', include('apps.freeswitch.urls')),
    ]
if 'apps.demonology' in settings.INSTALLED_APPS:
    # Создание демонов
    urlpatterns += [
        re_path(r'^demonology/', include('apps.demonology.urls')),
    ]
if 'apps.products' in settings.INSTALLED_APPS:
    # Товары/услуги
    urlpatterns += [
        re_path(r'^products/', include('apps.products.urls')),
    ]
if 'apps.promotion' in settings.INSTALLED_APPS:
    # Продвижение и сео
    urlpatterns += [
        re_path(r'^promotion/', include('apps.promotion.urls')),
    ]
if 'apps.personal' in settings.INSTALLED_APPS:
    # Пользователи сайта
    urlpatterns += [
        re_path(r'^personal/', include('apps.personal.urls')),
    ]
if 'apps.yandex' in settings.INSTALLED_APPS:
    # Яндекс сервисы
    urlpatterns += [
        re_path(r'^yandex/', include('apps.yandex.urls')),
    ]
if 'apps.shop' in settings.INSTALLED_APPS:
    # Магазин
    urlpatterns += [
        re_path(r'^shop/', include('apps.shop.urls')),
    ]
if 'apps.net_tools' in settings.INSTALLED_APPS:
    # Модуль сетевых утилит
    urlpatterns += [
        re_path(r'^net_tools/', include('apps.net_tools.urls')),
    ]
if 'apps.addresses' in settings.INSTALLED_APPS:
    # Адреса объектов
    urlpatterns += [
        re_path(r'^addresses/', include('apps.addresses.urls')),
    ]
if 'apps.contractors' in settings.INSTALLED_APPS:
    # Контрагенты
    urlpatterns += [
        re_path(r'^contractors/', include('apps.contractors.urls')),
    ]
if 'apps.jabber' in settings.INSTALLED_APPS:
    # Jabber XMPP
    urlpatterns += [
        re_path(r'^jabber/', include('apps.jabber.urls')),
    ]
if 'apps.former' in settings.INSTALLED_APPS:
    # Конструктор форм
    urlpatterns += [
        re_path(r'^former/', include('apps.former.urls')),
    ]
if 'djapian' in settings.INSTALLED_APPS:
    # DJAPIAN SEARCH
    from djapian.utils import load_indexes
    load_indexes()

# -------------------------------------------
# Обработка статических файлов под DEBUG=True
# -------------------------------------------
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# --------------
# Стат странички
# --------------
urlpatterns += [
    re_path(r'^', include('apps.flatcontent.urls_static')),
]

SITES/nosite/site/robots/views.py
# -*- coding:utf-8 -*-
import os
import json
import logging

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.urls import reverse, resolve
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt, csrf_protect

from apps.main_functions.catcher import json_pretty_print
from apps.main_functions.functions import object_fields
from apps.main_functions.model_helper import create_model_helper
from apps.main_functions.api_helper import ApiHelper, XlsxHelper
from apps.main_functions.string_parser import get_request_ip

from apps.main_functions.views_helper import (
    show_view,
    edit_view,
    search_view,
)
from apps.site.robots.models import (
    Robots,
    RobotProfiles,
    SearchQueries,
    Sites,
    TestScenarios,
    TEST_COMMANDS,
)

logger = logging.getLogger('main')

CUR_APP = 'robots'
robots_vars = {
    'singular_obj': 'Робот',
    'plural_obj': 'Роботы',
    'rp_singular_obj': 'робота',
    'rp_plural_obj': 'роботов',
    'template_prefix': 'robots_',
    'action_create': 'Создание',
    'action_edit': 'Редактирование',
    'action_drop': 'Удаление',
    'menu': 'robots',
    'submenu': 'robots',
    'show_urla': 'show_robots',
    'create_urla': 'create_robot',
    'edit_urla': 'edit_robot',
    'model': Robots,
    #'custom_model_permissions': Robots,
    #'select_related_list': ('name', ),
    'search_result_format': ('{} - {}', 'server_name ip'),
}

def api(request, action: str = 'robots'):
    """Апи-метод для получения всех данных
       :param request: HttpRequest
       :param action: к какой модели обращаемся
    """
    if action == 'test_scenarios':
        result = ApiHelper(request, test_scenarios_vars, CUR_APP)
    elif action == 'search_queries':
        result = ApiHelper(request, search_queries_vars, CUR_APP)
    elif action == 'sites':
        result = ApiHelper(request, sites_vars, CUR_APP)
    else:
        result = ApiHelper(request, robots_vars, CUR_APP)
    return result

def import_xlsx(request, action: str = 'search_queries'):
    """Апи-метод для сохранения данных из excel-файла
                     удаления данных по excel-файлу
       :param request: HttpRequest
       :param action: какую модель использовать
    """
    #if action == 'search_queries':
    #    result = XlsxHelper(request, search_queries_vars, CUR_APP)
    result = XlsxHelper(request, search_queries_vars, CUR_APP,
                        cond_fields = ['name', 'site__url'])
    return result

@login_required
def show_robots(request, *args, **kwargs):
    """Вывод роботов
       :param request: HttpRequest
    """
    mh_vars = robots_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP)
    context = mh.context
    # -----------------------------
    # Вся выборка только через аякс
    # -----------------------------
    if request.is_ajax():
        rows = mh.standard_show()
        result = []
        for row in rows:
            item = object_fields(row)
            item['actions'] = row.id
            item['folder'] = row.get_folder()
            item['thumb'] = row.thumb()
            item['imagine'] = row.imagine()
            result.append(item)
        if request.GET.get('page'):
            result = {'data': result,
                      'last_page': mh.raw_paginator['total_pages'],
                      'total_records': mh.raw_paginator['total_records'],
                      'cur_page': mh.raw_paginator['cur_page'],
                      'by': mh.raw_paginator['by'], }
        return JsonResponse(result, safe=False)
    template = '%stable.html' % (mh.template_prefix, )
    return render(request, template, context)

@login_required
def edit_robot(request, action: str, row_id: int = None, *args, **kwargs):
    """Создание/редактирование роботов
       :param request: HttpRequest
       :param action: действие над объектом (создание/редактирование/удаление)
       :param row_id: ид записи
    """
    mh_vars = robots_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP, action)
    row = mh.get_row(row_id)
    context = mh.context
    if mh.error:
        return redirect('%s?error=not_found' % (mh.root_url, ))
    if request.method == 'GET':
        if action == 'create':
            mh.breadcrumbs_add({
                'link': mh.url_create,
                'name': '%s %s' % (mh.action_create, mh.rp_singular_obj),
            })
        elif action == 'edit' and row:
            mh.breadcrumbs_add({
                'link': mh.url_edit,
                'name': '%s %s' % (mh.action_edit, mh.rp_singular_obj),
            })
        elif action == 'drop' and row:
            if mh.permissions['drop']:
                row.delete()
                mh.row = None
                context['success'] = '%s удален' % (mh.singular_obj, )
            else:
                context['error'] = 'Недостаточно прав'
    elif request.method == 'POST':
        pass_fields = ()
        mh.post_vars(pass_fields=pass_fields)
        if action == 'create' or (action == 'edit' and row):
            if action == 'create':
                if mh.permissions['create']:
                    mh.row = mh.model()
                    mh.save_row()
                    context['success'] = 'Данные успешно записаны'
                else:
                    context['error'] = 'Недостаточно прав'
            if action == 'edit':
                if mh.permissions['edit']:
                    mh.save_row()
                    context['success'] = 'Данные успешно записаны'
                else:
                    context['error'] = 'Недостаточно прав'
        elif action == 'img' and request.FILES:
            mh.uploads()
    if mh.row:
        context['row'] = object_fields(mh.row, pass_fields=('password', ))
        context['row']['folder'] = mh.row.get_folder()
        context['row']['thumb'] = mh.row.thumb()
        context['row']['imagine'] = mh.row.imagine()
        context['redirect'] = mh.get_url_edit()

    if request.is_ajax() or action == 'img':
        return JsonResponse(context, safe=False)
    template = '%sedit.html' % (mh.template_prefix, )
    return render(request, template, context)

@login_required
def robots_positions(request, *args, **kwargs):
    """Изменение позиций роботов
       :param request: HttpRequest
    """
    result = {}
    mh_vars = robots_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP, 'positions')
    result = mh.update_positions()
    return JsonResponse(result, safe=False)

def search_robots(request, *args, **kwargs):
    """Поиск роботов
       :param request: HttpRequest
    """
    return search_view(request,
                       model_vars = robots_vars,
                       cur_app = CUR_APP,
                       sfields = None, )

test_scenarios_vars = {
    'singular_obj': 'Сценарий',
    'plural_obj': 'Сценарии',
    'rp_singular_obj': 'сценария',
    'rp_plural_obj': 'сценариев',
    'template_prefix': 'test_scenarios/test_scenarios_',
    'action_create': 'Создание',
    'action_edit': 'Редактирование',
    'action_drop': 'Удаление',
    'menu': 'robots',
    'submenu': 'test_scenarios',
    'show_urla': 'show_test_scenarios',
    'create_urla': 'create_test_scenario',
    'edit_urla': 'edit_test_scenario',
    'model': TestScenarios,
    #'custom_model_permissions': TestScenarios,
    'select_related_list': ('robot', 'site'),
}

@login_required
def show_test_scenarios(request, *args, **kwargs):
    """Вывод сценариев
       :param request: HttpRequest
    """
    mh_vars = test_scenarios_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP)
    mh.select_related_add('robot')
    mh.select_related_add('site')
    context = mh.context
    # -----------------------------
    # Вся выборка только через аякс
    # -----------------------------
    if request.is_ajax():
        rows = mh.standard_show()
        result = []
        for row in rows:
            item = object_fields(row)
            item['actions'] = row.id
            item['folder'] = row.get_folder()
            item['thumb'] = row.thumb()
            item['imagine'] = row.imagine()
            result.append(item)
        if request.GET.get('page'):
            result = {'data': result,
                      'last_page': mh.raw_paginator['total_pages'],
                      'total_records': mh.raw_paginator['total_records'],
                      'cur_page': mh.raw_paginator['cur_page'],
                      'by': mh.raw_paginator['by'], }
        return JsonResponse(result, safe=False)
    template = '%stable.html' % (mh.template_prefix, )
    return render(request, template, context)

@login_required
def edit_test_scenario(request, action: str, row_id: int = None, *args, **kwargs):
    """Создание/редактирование сценария
       :param request: HttpRequest
       :param action: действие над объектом (создание/редактирование/удаление)
       :param row_id: ид записи
    """
    mh_vars = test_scenarios_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP, action)
    mh.select_related_add('robot')
    mh.select_related_add('site')
    row = mh.get_row(row_id)
    context = mh.context
    if row:
        try:
            context['commands'] = json.loads(row.commands)
        except Exception as e:
            logger.error(e)
    if mh.error:
        return redirect('%s?error=not_found' % (mh.root_url, ))
    context['test_commands'] = TEST_COMMANDS

    if request.method == 'GET':
        if action == 'create':
            mh.breadcrumbs_add({
                'link': mh.url_create,
                'name': '%s %s' % (mh.action_create, mh.rp_singular_obj),
            })
        elif action == 'edit' and row:
            mh.breadcrumbs_add({
                'link': mh.url_edit,
                'name': '%s %s' % (mh.action_edit, mh.rp_singular_obj),
            })

SITES/nosite/site/robots/templates/robots_admin_menu.html
{% if perms.robots.view_robots %}
<li{% ifequal menu 'robots' %} class="active"{% endifequal %} id="left_menu_robots_app">
  <a class="has-submenu" data-toggle="collapse-next" href="">
    <em class="fa fa-android"></em>
    <div class="label label-primary pull-right"><i class="fa fa-angle-down"></i></div>
    <span class="item-text">Роботы</span>
  </a>
  <ul class="nav collapse{% ifequal menu 'robots' %} in{% endifequal %}">

    <li{% ifequal submenu 'test_scenarios' %} class="active"{% endifequal %} id="left_menu_robots_app_test_scenarios">
      <a class="no-submenu" data-toggle="" href="{% url 'robots:show_test_scenarios' %}">
        <span class="item-text">Сценарии</span>
      </a>
    </li>
    <li{% ifequal submenu 'robot_profiles' %} class="active"{% endifequal %} id="left_menu_robots_app_robot_profiles">
      <a class="no-submenu" data-toggle="" href="{% url 'robots:show_robot_profiles' %}">
        <span class="item-text">Профили роботов</span>
      </a>
    </li>
    <li{% ifequal submenu 'robots' %} class="active"{% endifequal %} id="left_menu_robots_app_robots">
      <a class="no-submenu" data-toggle="" href="{% url 'robots:show_robots' %}">
        <span class="item-text">Роботы</span>
      </a>
    </li>
    <li{% ifequal submenu 'search_queries' %} class="active"{% endifequal %} id="left_menu_robots_app_search_queries">
      <a class="no-submenu" data-toggle="" href="{% url 'robots:show_search_queries' %}">
        <span class="item-text">Поисковые запросы</span>
      </a>
    </li>
    <li{% ifequal submenu 'sites' %} class="active"{% endifequal %} id="left_menu_robots_app_sites">
      <a class="no-submenu" data-toggle="" href="{% url 'robots:show_sites' %}">
        <span class="item-text">Сайты</span>
      </a>
    </li>
  </ul>
</li>
{% endif %}

SITES/nosite/site/robots/templates/robots_edit.html
{% extends "core/base.html" %}

{% block extrahead %}
{% endblock %}

{% block content %}
<h3>{{ singular_obj }}<br /><small>{% if row.id %}{{ action_edit }}{% else %}{{ action_create }}{% endif %} {{ rp_singular_obj }}</small></h3>

{% include "core/breadcrumbs.html" %}
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <form class="form-horizontal" method="post" action="{% if action == 'create' %}{{ url_create }}{% endif %}{% if action == 'edit' %}{{ url_edit }}{% endif %}" id="current_edit_form">
        <div class="panel-heading">{{ singular_obj }}</div>
        <div class="panel-body">
          {% csrf_token %}

          {% include "core/forms/row_name.html" %}

          <div class="form-group">
            <label class="col-lg-2 control-label">Версия selenium</label>
            <div class="col-lg-10">
              <input type="text" placeholder="Версия selenium" class="form-control" name="selenium_version" autocomplete="off" value="{% if row.selenium_version %}{{ row.selenium_version }}{% endif %}" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Версия chrome</label>
            <div class="col-lg-10">
              <input type="text" placeholder="Версия chrome" class="form-control" name="chrome_version" autocomplete="off" value="{% if row.chrome_version %}{{ row.chrome_version }}{% endif %}" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">IP</label>
            <div class="col-lg-10">
              <input type="text" placeholder="IP" class="form-control" name="ip" autocomplete="off" value="{% if row.ip %}{{ row.ip }}{% endif %}" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Сервер</label>
            <div class="col-lg-10">
              <input type="text" placeholder="Сервер" class="form-control" name="server_name" autocomplete="off" value="{% if row.server_name %}{{ row.server_name }}{% endif %}" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Свободное место, Gb</label>
            <div class="col-lg-10">
              <input type="text" placeholder="Свободное место" class="form-control" name="server_free_space" autocomplete="off" value="{% if row.server_free_space %}{{ row.server_free_space }}{% endif %}" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-2 control-label">Доп. информация</label>
            <div class="col-lg-10">
              <textarea placeholder="Доп. информация" class="form-control" name="info" autocomplete="off">{% if row.info %}{{ row.info }}{% endif %}</textarea>
            </div>
          </div>
          {% include "core/forms/row_image.html" %}
          {% include "core/forms/row_position.html" %}
          {% include "core/forms/row_is_active.html" %}
        </div>
        {% include "core/forms/footer_buttons.html" %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extrascripts %}
  <script src="/static/admin/js/parsley.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $("#current_edit_form").parsley();
      $("#current_edit_form").submit(function(e) {
        var $form = $(this);
        var msg = 'Произошла ошибка, обновите страничку';
        var status = 'danger'; // success, warning, info, danger
        $.ajax({
          type: $form.attr('method'),
          url: $form.attr('action'),
          data: $form.serialize()
        }).done(function(r) {
          if(r.error){
            msg = r.error;
          }else if(r.success){
            msg =  r.success;
            status = 'success';
            //$("#current_edit_form").attr("action", r.redirect);
            {% ifequal action 'create' %}window.location.href = r.redirect;{% endifequal %}
          }
          $.notify({
            message: msg,
          },{
            status: status,
          });
          // Обновление ссылок
          update_links(r);

        }).fail(function() {
          $.notify({
            message: msg,
          },{
            status: status,
          });
        });
        //отмена действия по умолчанию для кнопки submit
        e.preventDefault();
      });

      function update_links(r){
        var thumb = r['row']['thumb'];
        if(thumb === ''){
          thumb = '/static/img/empty.png';
        }
        $("#preview_img").attr("src", thumb + "?_=" + Date.now());
      }
      {% if row %}
        var progressbar = $('#progressbar-files'),
          bar         = progressbar.find('.progress-bar-files'),
          settings    = {
            action: '{% url "robots:edit_robot" "img" row.id %}', // upload url
            allow : '*.*',
            param: 'img',
            params: {csrfmiddlewaretoken: getCookie('csrftoken')},
            loadstart: function() {
              bar.css('width', '0%').text('0%');
              progressbar.removeClass('hidden');
            },
            progress: function(percent) {
              percent = Math.ceil(percent);
              bar.css('width', percent+'%').text(percent+'%');
            },
            allcomplete: function(response) {
              bar.css('width', '100%').text('100%');
              setTimeout(function(){
                progressbar.addClass('hidden');
              }, 750);
              // Upload Completed
              //alert(response);

              // Обновление ссылок
              var r = JSON.parse(response);
              update_links(r);
            }
          };
        var select = new $.upload.select($('#upload-select-files'), settings),
        drop   = new $.upload.drop($('#upload-drop-files'), settings);
      {% endif %}
    });
  </script>
{% endblock %}

SITES/nosite/site/robots/templates/robots_table.html
{% extends "core/base.html" %}

{% block extrahead %}
<link href="/static/datetimepicker/datepicker.min.css" rel="stylesheet"/>
{% endblock %}

{% block content %}
{% include "core/forms/default_create.html" %}

{% include "core/title/page_title_table.html" %}

{% include "core/breadcrumbs.html" %}
{% include "core/tabulator_table.html" %}
{% endblock %}

{% block extrascripts %}
<script type="text/javascript" src="/static/datetimepicker/datepicker.min.js"></script>
<script type="text/javascript">
var main_table = null;
var main_table_columns = null;
$(document).ready(function(){

  main_table_columns = [
    {% include "core/tabulator_cell/drag.html" %}
    {% include "core/tabulator_cell/id.html" %}
    {
      title: "IP",
      field: "ip",
      headerFilterPlaceholder: "IP",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 120,
    },
    {
      title: "Сервер",
      field: "server_name",
      headerFilterPlaceholder: "Сервер",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 120,
    },
    {
      title: "Обновлен",
      field: "updated",
      headerFilterPlaceholder: "Обновлен",
      headerFilter: "input",
      headerFilterFunc: "=",
      width: 120,
    },
    {
      title: "Версия selenium",
      field: "selenium_version",
      headerFilterPlaceholder: "Версия selenium",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 90,
    },
    {
      title: "Версия chrome",
      field: "chrome_version",
      headerFilterPlaceholder: "Версия selenium",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 90,
    },
    {
      title: "Свободно Gb",
      field: "server_free_space",
      headerFilterPlaceholder: "Свободно Gb",
      headerFilter: "input",
      headerFilterFunc: "like",
      width: 90,
    },
    {
      title: "Доп. информация",
      field: "info",
      headerSort: false,
      formatter: wordwrapFormatter,
      minWidth: 150,
      downloadTitle: "info",
    },
    {% include "core/tabulator_cell/image.html" %}
    {% include "core/tabulator_cell/is_active.html" %}
    {% include "core/tabulator_cell/position.html" %}
    {% include "core/tabulator_cell/actions.html" %}
  ];
  main_table = new Tabulator("#main-table", {
    {% include "core/tabulator_table_params.html" %}
    columns: main_table_columns,
  });
  $(".tabulator-headers .tabulator-col").each(function(){
    if($(this).attr("tabulator-field") === "updated"){
      $(this).find("input").datepicker({
        onSelect: function (fd, d, calendar) {
          calendar.hide();
        },
        position: "left top",
        todayButton: new Date(),
      });
    }
  });
});
</script>
{% endblock %}