apps/_demo_app/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'demo_app'
urlpatterns = [
    # получение по апи всех данных (т/к не секретно)
    url('^(?P<action>demo_model)/api/$', views.api, name='api'),
    # админка
    path('admin/', views.show_demo_model, name='show_demo_model'),
    url('^admin/(?P<action>create)/$', views.edit_demo_model, name='create_demo_model'),
    url('^admin/(?P<action>edit|drop|img)/(?P<row_id>[0-9]{1,11})/$', views.edit_demo_model, name='edit_demo_model'),
    path('admin/positions/', views.demo_model_positions, name='demo_model_positions'),
    # аякс-поиск
    path('demo_model/search/', views.search_demo_model, name='search_demo_model'),
]

conf/urls.py
from django.conf import settings
from django.urls import path, include, re_path
from django.shortcuts import redirect
from django.conf.urls import url


urlpatterns = [
    re_path(r'^admin/', include('apps.login.urls')),
    path('auth/', lambda request: redirect('/admin/', permanent=False)),
    # Стат. странички
    re_path(r'^flatcontent/', include('apps.flatcontent.urls')),
    # Файлы
    re_path(r'^files/', include('apps.files.urls')),
    # main_functions
    re_path(r'^', include('apps.main_functions.urls')),
    # Telegram
    re_path(r'^telegram/', include('apps.telegram.urls')),
    # статика
    re_path(r'^', include('apps.files.urls_static'))
]

# ---------------------------------
# Подключение приложений через .env
# ---------------------------------
if 'apps.site' in settings.INSTALLED_APPS:
    # Сайт
    urlpatterns.insert(1, re_path(r'^', include('apps.site.main.urls')))
# ---------------------------
# Подключаем custom site apps
# ---------------------------
for app in settings.INSTALLED_APPS:
    if app.startswith('apps.site.'):
        prefix = app.split('.')[-1]
        urlpatterns.insert(1, re_path(r'^%s/' % prefix, include('%s.urls' % app)))

if 'apps.afisha' in settings.INSTALLED_APPS:
    # Афиша
    urlpatterns += [
        re_path(r'^afisha/', include('apps.afisha.urls')),
    ]
if 'apps.spamcha' in settings.INSTALLED_APPS:
    from apps.spamcha.views import srdr_goto
    # Рассылки
    urlpatterns += [
        re_path(r'^spamcha/', include('apps.spamcha.urls')),
        # -----------------------------
        # /srdr/goto/.../ Переадресация
        # -----------------------------
        url('^srdr/goto/(?P<our_link>.+)/$', srdr_goto, name='srdr_goto'),
    ]
if 'apps.ws' in settings.INSTALLED_APPS:
    # websocket (chat)
    urlpatterns += [
        re_path(r'^ws/', include('apps.ws.urls')),
    ]
if 'apps.binary_com' in settings.INSTALLED_APPS:
    # binary.com
    urlpatterns += [
        re_path(r'^binary_com/', include('apps.binary_com.urls')),
    ]
if 'apps.languages' in settings.INSTALLED_APPS:
    # Переводы
    urlpatterns += [
        re_path(r'^languages/', include('apps.languages.urls')),
    ]
if 'apps.freeswitch' in settings.INSTALLED_APPS:
    # FREESWITCH
    urlpatterns += [
        re_path(r'^freeswitch/', include('apps.freeswitch.urls')),
    ]
if 'apps.demonology' in settings.INSTALLED_APPS:
    # Создание демонов
    urlpatterns += [
        re_path(r'^demonology/', include('apps.demonology.urls')),
    ]
if 'apps.products' in settings.INSTALLED_APPS:
    # Товары/услуги
    urlpatterns += [
        re_path(r'^products/', include('apps.products.urls')),
    ]
if 'apps.promotion' in settings.INSTALLED_APPS:
    # Продвижение и сео
    urlpatterns += [
        re_path(r'^promotion/', include('apps.promotion.urls')),
    ]
if 'apps.personal' in settings.INSTALLED_APPS:
    # Пользователи сайта
    urlpatterns += [
        re_path(r'^personal/', include('apps.personal.urls')),
    ]
if 'apps.yandex' in settings.INSTALLED_APPS:
    # Яндекс сервисы
    urlpatterns += [
        re_path(r'^yandex/', include('apps.yandex.urls')),
    ]
if 'apps.shop' in settings.INSTALLED_APPS:
    # Магазин
    urlpatterns += [
        re_path(r'^shop/', include('apps.shop.urls')),
    ]
if 'apps.net_tools' in settings.INSTALLED_APPS:
    # Модуль сетевых утилит
    urlpatterns += [
        re_path(r'^net_tools/', include('apps.net_tools.urls')),
    ]
if 'apps.addresses' in settings.INSTALLED_APPS:
    # Адреса объектов
    urlpatterns += [
        re_path(r'^addresses/', include('apps.addresses.urls')),
    ]
if 'apps.contractors' in settings.INSTALLED_APPS:
    # Контрагенты
    urlpatterns += [
        re_path(r'^contractors/', include('apps.contractors.urls')),
    ]
if 'apps.jabber' in settings.INSTALLED_APPS:
    # Jabber XMPP
    urlpatterns += [
        re_path(r'^jabber/', include('apps.jabber.urls')),
    ]
if 'apps.former' in settings.INSTALLED_APPS:
    # Конструктор форм
    urlpatterns += [
        re_path(r'^former/', include('apps.former.urls')),
    ]
if 'djapian' in settings.INSTALLED_APPS:
    # DJAPIAN SEARCH
    from djapian.utils import load_indexes
    load_indexes()

# -------------------------------------------
# Обработка статических файлов под DEBUG=True
# -------------------------------------------
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# --------------
# Стат странички
# --------------
urlpatterns += [
    re_path(r'^', include('apps.flatcontent.urls_static')),
]

apps/_demo_app/models.py
# -*- coding: utf-8 -*-
from django.db import models

from apps.main_functions.models import Standard

class DemoModel(Standard):
    """Модель пустышка для быстрого создания новой рабочей модельки для админки"""
    name = models.CharField(max_length=255, blank=True, null=True, db_index=True)

    class Meta:
        verbose_name = 'DemoApp - DemoModel'
        verbose_name_plural = 'DemoApp - DemoModels'
        #permissions = (
        #    ('view_obj', 'Просмотр объектов'),
        #    ('create_obj', 'Создание объектов'),
        #    ('edit_obj', 'Редактирование объектов'),
        #    ('drop_obj', 'Удаление объектов'),
        #)
        #default_permissions = []

    def save(self, *args, **kwargs):
        super(DemoModel, self).save(*args, **kwargs)

apps/_demo_app/views.py
# -*- coding:utf-8 -*-
import json

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.urls import reverse, resolve
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings

from apps.main_functions.functions import object_fields
from apps.main_functions.model_helper import create_model_helper
from apps.main_functions.api_helper import ApiHelper

from apps.main_functions.views_helper import (show_view,
                                              edit_view,
                                              search_view, )

from .models import DemoModel

CUR_APP = 'demo_app'
demo_model_vars = {
    'singular_obj': 'Объект',
    'plural_obj': 'Объекты',
    'rp_singular_obj': 'объекта',
    'rp_plural_obj': 'объектов',
    'template_prefix': 'demo_model_',
    'action_create': 'Создание',
    'action_edit': 'Редактирование',
    'action_drop': 'Удаление',
    'menu': 'demo_app',
    'submenu': 'demo_model',
    'show_urla': 'show_demo_model',
    'create_urla': 'create_demo_model',
    'edit_urla': 'edit_demo_model',
    'model': DemoModel,
    'search_result_format': ('{} (id={})', 'name id'),
    #'custom_model_permissions': DemoModel,
}

def api(request, action: str = 'demo_model'):
    """Апи-метод для получения всех данных
       :param request: HttpRequest
       :param action: к какой модели обращаемся
    """
    #if action == 'demo_model':
    #    return ApiHelper(request, demo_model_vars, CUR_APP)
    return ApiHelper(request, demo_model_vars, CUR_APP)

@login_required
def show_demo_model(request, *args, **kwargs):
    """Вывод объектов
       :param request: HttpRequest
    """
    return show_view(request,
                     model_vars = demo_model_vars,
                     cur_app = CUR_APP,
                     extra_vars = None, )

    mh_vars = demo_model_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP)
    context = mh.context

    # -----------------------------
    # Вся выборка только через аякс
    # -----------------------------
    if request.is_ajax():
        rows = mh.standard_show()
        result = []
        for row in rows:
            item = object_fields(row)
            item['actions'] = row.id
            item['folder'] = row.get_folder()
            item['thumb'] = row.thumb()
            item['imagine'] = row.imagine()
            result.append(item)
        if request.GET.get('page'):
            result = {'data': result,
                      'last_page': mh.raw_paginator['total_pages'],
                      'total_records': mh.raw_paginator['total_records'],
                      'cur_page': mh.raw_paginator['cur_page'],
                      'by': mh.raw_paginator['by'], }
        return JsonResponse(result, safe=False)
    template = '%stable.html' % (mh.template_prefix, )
    return render(request, template, context)

@login_required
def edit_demo_model(request, action: str, row_id: int = None, *args, **kwargs):
    """Создание/редактирование объекта
       :param request: HttpRequest
       :param action: действие над объектом (создание/редактирование/удаление)
       :param row_id: ид записи
    """
    return edit_view(request,
                     model_vars = demo_model_vars,
                     cur_app = CUR_APP,
                     action = action,
                     row_id = row_id,
                     extra_vars = None, )

    mh_vars = demo_model_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP, action)
    row = mh.get_row(row_id)
    context = mh.context # Контекст дозаполняется в get_row

    if mh.error:
        return redirect('%s?error=not_found' % (mh.root_url, ))
    if request.method == 'GET':
        if action == 'create':
            mh.breadcrumbs_add({
                'link': mh.url_create,
                'name': '%s %s' % (mh.action_create, mh.rp_singular_obj),
            })
        elif action == 'edit' and row:
            mh.breadcrumbs_add({
                'link': mh.url_edit,
                'name': '%s %s' % (mh.action_edit, mh.rp_singular_obj),
            })
        elif action == 'drop' and row:
            if mh.permissions['drop']:
                row.delete()
                mh.row = None
                context['success'] = '%s удален' % (mh.singular_obj, )
            else:
                context['error'] = 'Недостаточно прав'
    elif request.method == 'POST':
        pass_fields = ()
        mh.post_vars(pass_fields=pass_fields)
        if action == 'create' or (action == 'edit' and row):
            if action == 'create':
                if mh.permissions['create']:
                    mh.row = mh.model()
                    mh.save_row()
                    context['success'] = 'Данные успешно записаны'
                else:
                    context['error'] = 'Недостаточно прав'
            if action == 'edit':
                if mh.permissions['edit']:
                    mh.save_row()
                    context['success'] = 'Данные успешно записаны'
                else:
                    context['error'] = 'Недостаточно прав'
        elif action == 'img' and request.FILES:
            mh.uploads()
    if mh.row:
        context['row'] = object_fields(mh.row, pass_fields=('password', ))
        context['row']['folder'] = mh.row.get_folder()
        context['row']['thumb'] = mh.row.thumb()
        context['row']['imagine'] = mh.row.imagine()
        context['redirect'] = mh.get_url_edit()

    if request.is_ajax() or action == 'img':
        return JsonResponse(context, safe=False)
    template = '%sedit.html' % (mh.template_prefix, )
    return render(request, template, context)

@login_required
def demo_model_positions(request, *args, **kwargs):
    """Изменение позиций объектов
       :param request: HttpRequest
    """
    result = {}
    mh_vars = demo_model_vars.copy()
    mh = create_model_helper(mh_vars, request, CUR_APP, 'positions')
    result = mh.update_positions()
    return JsonResponse(result, safe=False)

def search_demo_model(request, *args, **kwargs):
    """Поиск объектов
       :param request: HttpRequest
    """
    return search_view(request,
                       model_vars = demo_model_vars,
                       cur_app = CUR_APP,
                       sfields = None, )

    result = {'results': []}
    mh = ModelHelper(DemoModel, request)
    mh_vars = demo_model_vars.copy()
    for k, v in mh_vars.items():
        setattr(mh, k, v)
    mh.search_fields = ('id', 'name')
    rows = mh.standard_show()
    for row in rows:
        result['results'].append({'text': '%s (%s)' % (row.name, row.id), 'id': row.id})
    if mh.raw_paginator['cur_page'] == mh.raw_paginator['total_pages']:
        result['pagination'] = {'more': False}
    else:
        result['pagination'] = {'more': True}
    return JsonResponse(result, safe=False)

apps/_demo_app/templates/demo_app_admin_menu.html
{% if perms.demo_app.view_demo_model %}
<li{% ifequal menu 'demo_model' %} class="active"{% endifequal %} id="left_menu_demo_app">
  <a{% comment %} class="has-submenu" data-toggle="collapse-next"{% endcomment %} href="{% url 'demo_app:show_demo_model' %}">
    <em class="fa fa-file"></em>
    <div class="label label-primary pull-right"><i class="fa fa-angle-down"></i></div>
    <span class="item-text">Объекты</span>
  </a>
  <ul class="nav collapse{% ifequal menu 'demo_app' %} in{% endifequal %}">
    <li{% ifequal submenu 'demo_model' %} class="active"{% endifequal %} id="left_menu_demo_app_objects_demo_model">
      <a class="no-submenu" data-toggle="" href="{% url 'demo_app:show_demo_model' %}">
        <span class="item-text">Объекты</span>
      </a>
    </li>
  </ul>
</li>
{% endif %}

apps/_demo_app/templates/demo_app_table.html
{% extends "core/base.html" %}

{% block extrahead %}
{% endblock %}

{% block content %}
{% include "core/forms/default_create.html" %}

{% include "core/title/page_title_table.html" %}
{% include "core/breadcrumbs.html" %}
{% include "core/tabulator_table.html" %}
{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
var main_table = null;
var main_table_columns = null;
$(document).ready(function(){

  var pathFormatter = function(cell, formatterParams, onRendered){
    //console.log(cell.getRow().getData());
    var data = cell.getRow().getData();
    var value = cell.getValue();
    var result = "<div class='padding-rl5 text-center'>";
    if(value){
      result += " <a style='white-space:normal;' class='btn' target='_blank' href='/media/" + data['folder'] + value + "'>" + value + "</a> ";
    }
    result += "</div>";
    return result;
  };

  main_table_columns = [
    {% include "core/tabulator_cell/drag.html" %}
    {% include "core/tabulator_cell/id.html" %}
    {% include "core/tabulator_cell/name.html" %}
    {
      title: "Описание",
      field: "desc",
      headerFilterPlaceholder: "Описание",
      headerFilter: "input",
      headerFilterFunc: "like",
      formatter: pathFormatter,
      width: 150,
    },
    {% include "core/tabulator_cell/image.html" %}
    {% include "core/tabulator_cell/is_active.html" %}
    {% include "core/tabulator_cell/position.html" %}
    {% include "core/tabulator_cell/actions.html" %}
  ];

  main_table = new Tabulator("#main-table", {
    {% include "core/tabulator_table_params.html" %}
    columns: main_table_columns,
  });
});
</script>
{% endblock %}

apps/_demo_app/templates/demo_model_edit.html
{% extends "core/base.html" %}

{% block extrahead %}
{% endblock %}

{% block content %}

{% include "core/title/page_title_edit.html" %}
{% include "core/breadcrumbs.html" %}
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <form class="form-horizontal" method="post" action="{% if action == 'create' %}{{ url_create }}{% endif %}{% if action == 'edit' %}{{ url_edit }}{% endif %}" id="current_edit_form">
        <div class="panel-heading">{{ singular_obj }}</div>
        <div class="panel-body">
          {% csrf_token %}
          {% include "core/forms/row_name.html" %}
          <div class="form-group">
            <label class="col-lg-2 control-label">Описание</label>
            <div class="col-lg-10">
              <input type="text" placeholder="Описание" class="form-control" name="name" value="{% if row.name %}{{ row.name }}{% endif %}" autocomplete="off" data-parsley-required>
            </div>
          </div>
          <!-- Привязанные странички -->
          <div class="form-group">
            <label class="col-lg-2 control-label">Наполнение, привязанные странички</label>
            <div class="col-lg-10">
              <select id="linkcontainer_select2" name="linkcontainer" autocomplete="off" multiple>
                {% for item in containers %}
                  <option value="{{ item.container.id }}" selected>{{ item.container.name }} #{{ item.container.id }} ({{ item.container.tag }})</option>
                {% endfor %}
              </select>
            </div>
          </div>
          {% include "core/forms/row_image.html" %}
          {% include "core/forms/row_position.html" %}
          {% include "core/forms/row_is_active.html" %}
        </div>
        {% include "core/forms/footer_buttons.html" %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extrascripts %}
  <script src="/static/admin/js/parsley.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $("#current_edit_form").parsley();
      $("#current_edit_form").submit(function(e) {
        var $form = $(this);
        var msg = 'Произошла ошибка, обновите страничку';
        var status = 'danger'; // success, warning, info, danger
        $.ajax({
          type: $form.attr('method'),
          url: $form.attr('action'),
          data: $form.serialize()
        }).done(function(r) {
          if(r.error){
            msg = r.error;
          }else if(r.success){
            msg =  r.success;
            status = 'success';
            //$("#current_edit_form").attr("action", r.redirect);
            {% ifequal action 'create' %}window.location.href = r.redirect;{% endifequal %}
          }
          $.notify({
            message: msg,
          },{
            status: status,
          });
          // Обновление ссылок
          update_links(r);

        }).fail(function() {
          $.notify({
            message: msg,
          },{
            status: status,
          });
        });
        //отмена действия по умолчанию для кнопки submit
        e.preventDefault();
      });

      $('#linkcontainer_select2').select2({
        placeholder: 'Какие странички привязать',
        width: '100%',
        tags: true,
        ajax: {
          url: "{% url 'flatcontent:search_containers' %}",

          data: function (params) {
            var query = {
              q: params.term,
              without_templates: 1,
              without_menus: 1,
              without_main: 1,
              page: params.page || 1,
            }
            return query;
          },

          //data: "without_templates=1&without_menus=1&without_main=1",
          cache: false,
          dataType: 'json',
        }
      });

      function update_links(r){
        var thumb = r['row']['thumb'];
        if(thumb === ''){
          thumb = '/static/img/empty.png';
        }
        $("#preview_img").attr("src", thumb + "?_=" + Date.now());
      }
      {% if row %}
        var progressbar = $('#progressbar-files'),
          bar         = progressbar.find('.progress-bar-files'),
          settings    = {
            action: '{% url "demo_app:edit_demo_model" "img" row.id %}', // upload url
            allow : '*.*',
            param: 'img',
            params: {csrfmiddlewaretoken: getCookie('csrftoken')},
            loadstart: function() {
              bar.css('width', '0%').text('0%');
              progressbar.removeClass('hidden');
            },
            progress: function(percent) {
              percent = Math.ceil(percent);
              bar.css('width', percent+'%').text(percent+'%');
            },
            allcomplete: function(response) {
              bar.css('width', '100%').text('100%');
              setTimeout(function(){
                progressbar.addClass('hidden');
              }, 750);
              // Upload Completed
              //alert(response);

              // Обновление ссылок
              var r = JSON.parse(response);
              update_links(r);
            }
          };
        var select = new $.upload.select($('#upload-select-files'), settings),
        drop   = new $.upload.drop($('#upload-drop-files'), settings);
      {% endif %}
    });
  </script>
{% endblock %}

apps/_demo_app/templates/demo_model_table.html
{% extends "core/base.html" %}

{% block extrahead %}
{% endblock %}

{% block content %}
{% include "core/forms/default_create.html" %}

{% include "core/title/page_title_table.html" %}
{% include "core/breadcrumbs.html" %}
{% include "core/tabulator_table.html" %}
{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
var main_table = null;
var main_table_columns = null;
$(document).ready(function(){

  var pathFormatter = function(cell, formatterParams, onRendered){
    //console.log(cell.getRow().getData());
    var data = cell.getRow().getData();
    var value = cell.getValue();
    var result = "<div class='padding-rl5 text-center'>";
    if(value){
      result += " <a style='white-space:normal;' class='btn' target='_blank' href='/media/" + data['folder'] + value + "'>" + value + "</a> ";
    }
    result += "</div>";
    return result;
  };

  main_table_columns = [
    {% include "core/tabulator_cell/drag.html" %}
    {% include "core/tabulator_cell/id.html" %}
    {% include "core/tabulator_cell/name.html" %}
    {
      title: "Описание",
      field: "desc",
      headerFilterPlaceholder: "Описание",
      headerFilter: "input",
      headerFilterFunc: "like",
      formatter: pathFormatter,
      width: 150,
    },
    {% include "core/tabulator_cell/image.html" %}
    {% include "core/tabulator_cell/is_active.html" %}
    {% include "core/tabulator_cell/position.html" %}
    {% include "core/tabulator_cell/actions.html" %}
  ];

  main_table = new Tabulator("#main-table", {
    {% include "core/tabulator_table_params.html" %}
    columns: main_table_columns,
  });
});
</script>
{% endblock %}